# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'referenda' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for referenda
  pod 'Amplitude-iOS', '~> 4.3.1'
  #pod 'Stripe'
  pod "SquareInAppPaymentsSDK"

  #pod 'ReactNativePayments', :path => '../node_modules/react-native-payments'

  #pod 'RNSquareInAppPayments', :path => '../node_modules/react-native-square-in-app-payments'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
  end

  #target 'referendaTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

end
